modules/members/views.py
import csv
from datetime import datetime

from flask import Blueprint, Response, abort, flash, render_template
from flask_login import current_user, login_required

from app import db
from modules.user.models import User

members_bp = Blueprint('members', __name__, url_prefix='/members')

@members_bp.route('/all-members')
@login_required
def all_members():
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
    members = User.query.all()
    
    department_order = [
        'Communication and Marketing',
        'Creative',
        'Event Management',
        'Finance',
        'Human Resources',
        'Press Release and Publications',
        'Research and Development'
    ]
    
    position_order = [
        'Governing Body Members',
        'Director',
        'Assistant Director',
        'Senior Executive',
        'Executive',
        'General Member'
    ]
    
    members_sorted = sorted(members, key=lambda x: (department_order.index(x.department if x.department != 'Governing Body Members' else ''), position_order.index(x.designation)))
    
    return render_template('members/all_members.html', members=members_sorted)


@members_bp.route('/member/<int:user_id>')
@login_required
def user_profile(user_id):
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
    user = User.query.get_or_404(user_id)
    return render_template('members/member_details.html', user=user)


@members_bp.route('/export_csv')
@login_required
def export_csv():
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
    members = User.query.all()
    with open('members.csv', mode='w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Student ID','Name', 'Email', 'Phone', 'Department', 'Designation'])
        for member in members:
            writer.writerow([member.student_id, member.name, member.email, member.phone, member.department, member.designation])
    
    flash('Excel file has been exported successfully!', 'success')
    return Response(open('members.csv', 'r'), mimetype='text/csv', headers={"Content-disposition":"attachment; filename=members.csv"})

templates/members/all_members.html
{% extends "base.html" %} {% block title %}All Members{% endblock %} {% block
content %}
<div class="container mx-auto min-h-screen">
  <div>
    <h1 class="my-8 text-3xl font-bold text-center">All Members</h1>

    <!-- Search Field and Filters Row -->
    <div class="flex mb-4 items-center">
      <!-- Search Field -->
      <div class="w-1/2 mr-4">
        <label for="search" class="block">Search by Name:</label>
        <input
          type="text"
          id="search"
          placeholder="Search members..."
          class="border rounded-md px-4 py-2 w-full"
        />
      </div>

      <!-- Designation Filter -->
      <div class="w-1/4 mr-4">
        <label for="designation" class="block">Filter by Designation:</label>
        <select id="designation" class="border rounded-md px-4 py-2 w-full">
          <option value="">All</option>
          <option value="Governing Body Members">Governing Body Members</option>
          <option value="Director">Director</option>
          <option value="Assistant Director">Assistant Director</option>
          <option value="Senior Executive">Senior Executive</option>
          <option value="Executive">Executive</option>
          <option value="General Member">General Member</option>
        </select>
      </div>

      <!-- Department Filter -->
      <div class="w-1/4">
        <label for="department" class="block">Filter by Department:</label>
        <select id="department" class="border rounded-md px-4 py-2 w-full">
          <option value="">All</option>
          <option value="Communication and Marketing">
            Communication and Marketing
          </option>
          <option value="Creative">Creative</option>
          <option value="Event Management">Event Management</option>
          <option value="Finance">Finance</option>
          <option value="Human Resources">Human Resources</option>
          <option value="Press Release and Publications">
            Press Release and Publications
          </option>
          <option value="Research and Development">
            Research and Development
          </option>
        </select>
      </div>
      <div class="mt-4 ml-3">
        <button
          onclick="window.location.href='{{ url_for('members.export_csv') }}'"
          class="p-2 bg-[#2A5CAA] text-white border border-transparent rounded-md hover:bg-[#09377c] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="22"
            height="23"
            fill="currentColor"
            class="bi bi-person-down"
            viewBox="0 0 16 16"
          >
            <path
              d="M12.5 9a3.5 3.5 0 1 1 0 7 3.5 3.5 0 0 1 0-7m.354 5.854 1.5-1.5a.5.5 0 0 0-.708-.708l-.646.647V10.5a.5.5 0 0 0-1 0v2.793l-.646-.647a.5.5 0 0 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4"
            ></path>
            <path
              d="M8.256 14a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1z"
            ></path>
          </svg>
        </button>
      </div>
    </div>

    <!-- Members Table -->
    <div class="bg-white shadow-md rounded-lg overflow-x-auto">
      <table class="table-auto w-full" id="members-table">
        <thead class="bg-gray-200">
          <tr>
            <th class="px-6 py-3 text-center">Student ID</th>
            <th class="px-6 py-3 text-center">Name</th>
            <th class="px-6 py-3 text-center">BUAIC Department</th>
            <th class="px-6 py-3 text-center">BUAIC Designation</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          {% for member in members %}
          <tr
            class="hover:bg-gray-100 member-row hover:cursor-pointer"
            data-url="{{ url_for('members.user_profile', user_id=member.id) }}"
          >
            <td class="px-6 py-4 text-center">{{ member.student_id }}</td>
            <td class="px-6 py-4 text-center">{{ member.name }}</td>
            <td class="px-6 py-4 text-center">{{ member.department }}</td>
            <td class="px-6 py-4 text-center">{{ member.designation }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
  $(document).ready(function () {
    $("#search").on("input", function () {
      var query = $(this).val().toLowerCase();

      $("tbody tr").each(function () {
        var id = $(this).find("td:nth-child(1)").text().toLowerCase();
        var name = $(this).find("td:nth-child(2)").text().toLowerCase();
        var department = $(this).find("td:nth-child(3)").text().toLowerCase();
        var designation = $(this).find("td:nth-child(4)").text().toLowerCase();

        if (id.includes(query) || name.includes(query)) {
          $(this).show();
        } else {
          $(this).hide();
        }
      });
    });

    $("#designation, #department").change(function () {
      var designationValue = $("#designation").val().toLowerCase();
      var departmentValue = $("#department").val().toLowerCase();

      $("tbody tr").each(function () {
        var designation = $(this).find("td:nth-child(4)").text().toLowerCase();
        var department = $(this).find("td:nth-child(3)").text().toLowerCase();

        if (
          (designationValue === "" || designation === designationValue) &&
          (departmentValue === "" || department === departmentValue)
        ) {
          $(this).show();
        } else {
          $(this).hide();
        }
      });
    });
  });
</script>

<script>
  $(document).ready(function () {
    $(".member-row").click(function () {
      var url = $(this).data("url");
      if (url) {
        window.location.href = url;
      }
    });
  });
</script>

{% endblock %}

templates/members/member_details.html
{% extends "base.html" %} {% block title %}User Profile - {{ user.name }}{%
endblock %} {% block content %}
<div class="container mx-auto min-h-screen">
  <div>
    <h1 class="my-8 text-3xl font-bold text-center">
      User Profile - {{ user.name }}
    </h1>
    <div class="bg-white shadow-md rounded-lg p-6 w-1/3">
      <div class="grid grid-cols-2 gap-4">
        <div>
          <p class="text-gray-600">
            <strong>Student ID:</strong> {{ user.student_id }}
          </p>
          <p class="text-gray-600"><strong>Email:</strong> {{ user.email }}</p>
          <p class="text-gray-600">
            <strong>Department:</strong> {{ user.department }}
          </p>
          <p class="text-gray-600">
            <strong>Designation:</strong> {{ user.designation }}
          </p>
          <p class="text-gray-600"><strong>Phone:</strong> {{ user.phone }}</p>
          <p class="text-gray-600">
            <strong>Semester:</strong> {{ user.semester }}
          </p>
          <p class="text-gray-600">
            <strong>Date of Birth:</strong> {{ user.dob }}
          </p>
          <p class="text-gray-600">
            <strong>Blood Group:</strong> {{ user.blood_group }}
          </p>
          <p class="text-gray-600">
            <strong>Joined Semester:</strong> {{ user.joined_semester }}
          </p>
        </div>
        <div></div>
      </div>
    </div>
  </div>
</div>
{% endblock %}