modules/polls/models.py
from datetime import datetime

from app import db
from modules.user import User


class Polls(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.String(100), nullable=False)
    option1 = db.Column(db.String(100), nullable=False)
    option2 = db.Column(db.String(100), nullable=False)
    option3 = db.Column(db.String(100), nullable=True)
    option4 = db.Column(db.String(100), nullable=True)
    count_option1 = db.Column(db.Integer, nullable=False, default=0)
    count_option2 = db.Column(db.Integer, nullable=False, default=0)
    count_option3 = db.Column(db.Integer, nullable=True, default=0)
    count_option4 = db.Column(db.Integer, nullable=True, default=0)
    created_at = db.Column(db.DateTime, default=datetime.now)
    
    def get_poll(self):
        return str(self.id, self.question, self.option1, self.option2, self.option3, self.option4, self.count_option1, self.count_option2, self.count_option3, self.count_option4, self.created_at)

class Voted(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    poll_id = db.Column(db.Integer, db.ForeignKey('polls.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    voted_at = db.Column(db.DateTime, default=datetime.now)
    
    def get_voted(self):
        return str(self.id, self.poll_id, self.user_id, self.voted_at)
    
    def __repr__(self):
        return f"Voted('{self.id}', '{self.poll_id}', '{self.user_id}', '{self.voted_at}')"

modules/polls/__init__.py
#bluprint
from flask import Blueprint, flash

polls_bp = Blueprint('polls', __name__, template_folder='templates', static_folder='static')

from . import views

modules/polls/views.py
from datetime import datetime

from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   session, url_for)
from flask_login import current_user, login_manager, login_required

from app import db, login_manager

from . import polls_bp
from .models import Polls, Voted


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@polls_bp.route('/polls/create_poll', methods=['GET', 'POST'])
@login_required
def create_poll():
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
    if request.method == 'POST':
        question = request.form.get('question')
        option1 = request.form.get('option1')
        option2 = request.form.get('option2')
        option3 = request.form.get('option3')
        option4 = request.form.get('option4')
        
        if not option1 or not option2:
            flash('Options 1 and 2 are required.', 'danger')
            return redirect(url_for('polls.create_poll'))

        poll = Polls(question=question, option1=option1, option2=option2, option3=option3, option4=option4)
        db.session.add(poll)
        db.session.commit()
        
        flash('Poll created successfully!', 'success')
        return redirect(url_for('polls.view_polls'))
    
    return render_template('polls/create_poll.html')


@polls_bp.route('/polls/view_polls')
@login_required
def view_polls():
    polls = Polls.query.all()
    polls_dict = {}

    for poll in polls:
        polls_dict[poll.id] = {'option1': poll.option1,
                               'option2': poll.option2,
                                'option3': poll.option3,
                                'option4': poll.option4,
                                'count_option1': poll.count_option1,
                                'count_option2': poll.count_option2,
                                'count_option3': poll.count_option3,
                                'count_option4': poll.count_option4
                               }
            
    
    return render_template('polls/view_polls.html', polls=polls, json_polls=polls_dict)


@polls_bp.route('/polls/vote/<int:poll_id>', methods=['GET', 'POST'])
@login_required
def vote(poll_id):
    poll = Polls.query.get(poll_id)
    question = poll.question
    options = [poll.option1, poll.option2, poll.option3, poll.option4]
    user_voted = Voted.query.filter_by(poll_id=poll_id, user_id=current_user.id).first()
    
    if request.method == 'POST' and not user_voted:

        option = request.form.get('option')
        
        if option == options[0]:
            poll.count_option1 += 1
            
        elif option == options[1]:
            poll.count_option2 += 1
            
        elif option == options[2]:
            poll.count_option3 += 1
            
        elif option == options[3]:
            poll.count_option4 += 1
             
        voted = Voted(poll_id=poll_id, user_id=current_user.id)

        db.session.add(voted)
        
        db.session.commit()
        
        flash('Voted successfully!', 'success')
        return redirect(url_for('polls.view_polls'))
    
    if user_voted:
            flash('You have already voted!', 'danger')
            return redirect(url_for('polls.view_polls'))
        
    return render_template('polls/vote.html', poll=poll, question=question, options=options, user_voted=user_voted)


@polls_bp.route('/polls/delete_poll/<int:poll_id>')
@login_required
def delete_poll(poll_id):
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
    poll = Polls.query.get(poll_id)
    voted = Voted.query.filter_by(poll_id=poll_id).all()

    for vote in voted:
        db.session.delete(vote)
    
    db.session.commit()
    db.session.delete(poll)
    db.session.commit()
    
    flash('Poll deleted successfully!', 'success')
    return redirect(url_for('polls.view_polls'))

templates/polls/create_poll.html
{% extends 'base.html' %} {% block title %}Create Poll{% endblock %} {% block
content %}
<div class="container mx-auto mt-8 flex justify-center items-center">
  <div class="bg-white p-8 shadow-md rounded-md w-96">
    <h1 class="text-3xl font-bold mb-6">Create new Poll</h1>

    <form method="POST" action="{{ url_for('polls.create_poll')}}">
      <div class="mb-4">
        <label for="question" class="block text-gray-700 font-bold mb-2"
          >Question:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full"
          id="question"
          name="question"
        />
      </div>
      <div class="mb-4">
        <label for="option1" class="block text-gray-700 font-bold mb-2"
          >Option 1:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full"
          id="option1"
          name="option1"
        />
      </div>
      <div class="mb-4">
        <label for="option2" class="block text-gray-700 font-bold mb-2"
          >Option 2:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full"
          id="option2"
          name="option2"
        />
      </div>
      <div class="mb-4">
        <label for="option3" class="block text-gray-700 font-bold mb-2"
          >Option 3:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full"
          id="option3"
          name="option3"
        />
      </div>
      <div class="mb-4">
        <label for="option4" class="block text-gray-700 font-bold mb-2"
          >Option 4:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full"
          id="option4"
          name="option4"
        />
      </div>
      <button
        type="submit"
        class="bg-[#2A5CAA] text-white py-2 px-4 rounded-md hover:bg-[#09377c] w-full"
      >
        Submit
      </button>
    </form>
  </div>
</div>
{% endblock %}

templates/polls/view_polls.html
{% extends "base.html" %} {% block title %}All Polls{% endblock %} {% block
content %}
<div class="container mx-auto min-h-screen">
  <div>
    <h1 class="my-8 text-3xl font-bold text-center">All Polls</h1>
    <div class="-mt-20">
      <div
        class="grid grid-cols-1 gap-8 mt-8 xl:mt-16 md:grid-cols-2 xl:grid-cols-3"
      >
        {% for poll in polls %}
        <div class="each-poll" id="poll_{{ poll.id }}">
          <div x-data="app({{ poll.id }})" x-cloak class="px-4 cursor-pointer">
            <div class="max-w-lg mx-auto py-24">
              <div class="shadow p-6 rounded-lg bg-white">
                <div class="md:flex md:justify-between md:items-center">
                  <div>
                    <h2 class="text-xl text-gray-800 font-bold leading-tight">
                      {{ poll.question }}
                    </h2>
                  </div>

                  <!-- Legends -->
                  <div class="mb-4">
                    <div class="flex items-center">
                      <div class="w-2 h-2 bg-[#2A5CAA] mr-2 rounded-full"></div>
                      <div class="text-sm text-gray-700">Votes</div>
                    </div>
                  </div>
                </div>

                <div class="line my-8 relative">
                  <!-- Tooltip -->
                  <template x-if="tooltipOpen == true">
                    <div
                      x-ref="tooltipContainer"
                      class="p-0 m-0 z-10 shadow-lg rounded-lg absolute h-auto block"
                      :style="`bottom: ${tooltipY}px; left: ${tooltipX}px`"
                    >
                      <div class="shadow-xs rounded-lg bg-white p-2">
                        <div class="flex items-center justify-between text-sm">
                          <div>Votes:</div>
                          <div class="font-bold ml-2">
                            <span x-html="tooltipContent"></span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </template>

                  <!-- Bar Chart -->
                  <div class="flex -mx-2 items-end mb-2">
                    <template x-for="data in chartData">
                      <div
                        class="px-2 {% if poll.option4 %} w-1/4 {% elif poll.option3 %} w-1/3 {% else %} w-1/2 {% endif %}"
                      >
                        <div
                          :style="`height: ${data}rem`"
                          class="transition ease-in duration-200 bg-[#2A5CAA] hover:bg-[#09377c] relative"
                          @mouseenter="showTooltip($event); tooltipOpen = true"
                          @mouseleave="hideTooltip($event)"
                        >
                          <div
                            x-text="data"
                            class="text-center absolute top-0 left-0 right-0 -mt-6 text-gray-800 text-sm"
                          ></div>
                        </div>
                      </div>
                    </template>
                  </div>

                  <!-- Labels -->
                  <div
                    class="border-t border-gray-400 mx-auto"
                    :style="`height: 1px; width: ${ 100 - 1/chartData.length*100 + 3}%`"
                  ></div>
                  <div class="flex -mx-2 items-end">
                    <template x-for="data in labels">
                      <div
                        class="px-2 {% if poll.option4 %} w-1/4 {% elif poll.option3 %} w-1/3 {% else %} w-1/2 {% endif %}"
                      >
                        <div class="bg-red-600 relative">
                          <div
                            class="text-center absolute top-0 left-0 right-0 h-2 -mt-px bg-gray-400 mx-auto"
                            style="width: 1px"
                          ></div>
                          <div
                            x-text="data"
                            class="text-center absolute top-0 left-0 right-0 mt-3 text-gray-700 text-sm"
                          ></div>
                        </div>
                      </div>
                    </template>
                  </div>
                </div>
                <div class="mt-16 flex justify-center items-center gap-2">
                  {% if user_voted %} {% else %}
                  <button
                    class="bg-[#2A5CAA] hover:bg-[#09377c] text-white font-bold py-2 px-4 rounded"
                    onclick="location.href='/polls/vote/{{poll.id}}'"
                  >
                    Vote
                  </button>
                  {% endif %} {% if current_user.designation in ['President',
                  'Vice President', 'General Secretary', 'Director', 'Assistant
                  Director'] %}
                  <button
                    class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
                    onclick="location.href='/polls/delete_poll/{{poll.id}}'"
                  >
                    Delete
                  </button>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>

          <script>
            function app(pollId) {
              var jsonPolls = {{ json_polls|tojson }};
              var dynamicChartData = [];
              var dynamicLabels = [];
              var thisPoll = jsonPolls[pollId];
              dynamicChartData.push(thisPoll.count_option1);
              dynamicLabels.push(thisPoll.option1);
              dynamicChartData.push(thisPoll.count_option2);
              dynamicLabels.push(thisPoll.option2);

              if (thisPoll.option3) {
                dynamicChartData.push(thisPoll.count_option3);
                dynamicLabels.push(thisPoll.option3);
              }

              if (thisPoll.option4) {
                dynamicChartData.push(thisPoll.count_option4);
                dynamicLabels.push(thisPoll.option4);
              }

              return {
                chartData: dynamicChartData,
                labels: dynamicLabels,
                tooltipContent: "",
                tooltipOpen: false,
                tooltipX: 0,
                tooltipY: 0,
                showTooltip(e) {
                  this.tooltipContent = e.target.textContent;
                  this.tooltipX = e.target.offsetLeft - e.target.clientWidth;
                  this.tooltipY = e.target.clientHeight + e.target.clientWidth;
                },
                hideTooltip(e) {
                  this.tooltipContent = "";
                  this.tooltipOpen = false;
                  this.tooltipX = 0;
                  this.tooltipY = 0;
                },
              };
            }
          </script>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/polls/vote.html
{% extends 'base.html' %} {% block title %}Vote{% endblock %} {% block content
%}
<div class="container mx-auto mt-8 flex justify-center items-center">
  <div class="bg-white p-8 shadow-md rounded-md w-96">
    <h1 class="text-3xl font-bold mb-6">Vote</h1>

    <form
      method="post"
      action="{{ url_for('polls.vote', poll_id=poll.id) }}"
      class="space-y-4"
    >
      <div>
        <h2 class="text-lg font-bold mb-2">{{ question }}</h2>
      </div>
      <div>
        {% for option in options %} {% if option %}
        <div class="flex items-center mb-2">
          <input
            type="radio"
            id="{{ option }}"
            name="option"
            value="{{ option }}"
            class="mr-2"
          />
          <label for="{{ option }}" class="text-sm">{{ option }}</label>
        </div>
        {% endif %} {% endfor %}
      </div>

      <button
        type="submit"
        class="w-full py-2 px-4 bg-[#2A5CAA] text-white rounded-md hover:bg-[#09377c]"
      >
        Vote
      </button>
    </form>
  </div>
</div>
{% endblock %}