modules/event/models.py
from datetime import datetime

from flask_bcrypt import Bcrypt

from app import db, login_manager, migrate

bcrypt = Bcrypt()

class Event(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(255), nullable=False)
    start_date = db.Column(db.DateTime, nullable=False)
    end_date = db.Column(db.DateTime, nullable=False)
    venue = db.Column(db.String(100), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.now)
    
    def get_event(self):
        return self.title

modules/event/__init__.py
from flask import Blueprint, flash

event_bp = Blueprint('event', __name__, template_folder='templates', static_folder='static', url_prefix='/event')

from . import views

modules/event/views.py
from datetime import datetime
from xml.dom import ValidationErr

from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   session, url_for)
from flask_login import (LoginManager, current_user, login_manager,
                         login_required, login_user, logout_user)

from app import db, login_manager
from modules.attendance.models import Attendance
from modules.intake.models import Semester
from modules.user.models import User

from . import event_bp
from .models import Event


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@event_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
        
    if request.method == 'POST':
        title = request.form['title'].upper()
        description = request.form['description']
        start_date = request.form['start_datetime']
        end_date = request.form['end_datetime']
        venue = request.form['venue']
        
        start_date = datetime.strptime(start_date, "%Y-%m-%dT%H:%M")
        if start_date < datetime.now():
            flash('Start date cannot be before today', 'danger')
            return redirect(url_for('event.create'))

        end_date = datetime.strptime(end_date, "%Y-%m-%dT%H:%M")
        if end_date < start_date:
            flash('End date cannot be before start date', 'danger')
            return redirect(url_for('event.create'))

        event = Event(title=title, description=description, start_date=start_date, end_date=end_date, venue=venue)
        db.session.add(event)
        db.session.commit()

        flash('Event created successfully!', 'success')
        return redirect(url_for('event.list'))

    return render_template('events/create.html')


@event_bp.route('/list')
@login_required
def list():
    
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
        
    events = Event.query.order_by(Event.start_date.desc()).all()
    now = datetime.now()
    
    return render_template('events/list.html', events=events, now=now)


@event_bp.route('/delete/<int:event_id>', methods=['GET', 'POST'])
@login_required
def delete(event_id):
    if current_user.designation not in ['Governing Body', 'President', 'Vice President', 'Secretary', 'Treasurer', 'Director', 'Assistant Director']:
        abort(403)
        
    if request.method == 'POST':
        event = Event.query.get(event_id)
        attendances = Attendance.query.filter_by(event_id=event_id).all()
        
        for attendance in attendances:
            db.session.delete(attendance)
        
        db.session.delete(event)
        db.session.commit()

        flash('Event deleted successfully!', 'success')
        return redirect(url_for('event.list'))
    

def validate_start_date(start_date):
    start_date = datetime.strptime(start_date, "%Y-%m-%dT%H:%M")
    if start_date < datetime.now():
        flash('Start date can not be before today')
        return redirect(url_for('event.create'))


templates/events/create.html
{% extends 'base.html' %} {% block title %}Create Event{% endblock %} {% block
content %}
<div class="container mx-auto mt-8 flex justify-center items-center">
  <div class="bg-white p-8 shadow-md rounded-md w-96">
    <h1 class="text-3xl font-bold mb-6">Create Event</h1>
    <form method="POST" action="{{ url_for('event.create')}}" class="space-y-4">
      <div>
        <label for="title" class="block text-gray-700 font-bold mb-2"
          >Title:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full focus:outline-none focus:border-blue-500"
          id="title"
          name="title"
        />
      </div>
      <div>
        <label for="description" class="block text-gray-700 font-bold mb-2"
          >Description:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full focus:outline-none focus:border-blue-500"
          id="description"
          name="description"
        />
      </div>
      <div>
        <label for="start_datetime" class="block text-gray-700 font-bold mb-2"
          >Start Date & Time:</label
        >
        <input
          type="datetime-local"
          class="border border-gray-300 rounded-md py-2 px-3 w-full focus:outline-none focus:border-blue-500"
          id="start_datetime"
          name="start_datetime"
        />
      </div>
      <div>
        <label for="end_datetime" class="block text-gray-700 font-bold mb-2"
          >End Date & Time:</label
        >
        <input
          type="datetime-local"
          class="border border-gray-300 rounded-md py-2 px-3 w-full focus:outline-none focus:border-blue-500"
          id="end_datetime"
          name="end_datetime"
        />
      </div>
      <div>
        <label for="venue" class="block text-gray-700 font-bold mb-2"
          >Venue:</label
        >
        <input
          type="text"
          class="border border-gray-300 rounded-md py-2 px-3 w-full focus:outline-none focus:border-blue-500"
          id="venue"
          name="venue"
        />
      </div>
      <br />

      <button
        type="submit"
        class="bg-[#2A5CAA] text-white p-2 rounded-md hover:bg-[#09377c] w-full"
      >
        Submit
      </button>
    </form>
  </div>
</div>
{% endblock %}

templates/events/list.html
{% extends 'base.html' %} {% block title %}Events{% endblock %} {% block content
%}
<div class="container mx-auto min-h-screen">
  <div>
    <h1 class="my-8 text-3xl font-bold text-center">Events</h1>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
      {% for event in events %} {% if event.end_date >= now %}
      <div
        class="rounded-md overflow-hidden shadow-md bg-[#2A5CAA] text-white/95 cursor-pointer"
      >
        <div
          class="p-4"
          onclick="window.location.href='{{ url_for('attendance.record_attendance', event_id=event.id) }}'"
        >
          <h2 class="text-lg font-bold mb-2">{{ event.title }}</h2>
          <p class="text-gray-200 mb-2">{{ event.description }}</p>
          <p class="text-gray-200 mb-2">
            <strong>Start Time:</strong> {{ event.start_date}}
          </p>
          <p class="text-gray-200 mb-2">
            <strong>End Time:</strong> {{ event.end_date}}
          </p>
        </div>

        <div class="p-4 flex justify-end mr-4">
          <div>
            <form
              action="{{ url_for('event.delete', event_id=event.id) }}"
              method="post"
            >
              <button
                type="submit"
                class="text-red-700 font-bold py-2 px-3 rounded-md bg-red-200"
              >
                Delete
              </button>
            </form>
          </div>
        </div>
      </div>
      {% else %}
      <div class="rounded-md overflow-hidden shadow-md bg-white text-black/95">
        <div class="p-4">
          <h2 class="text-lg font-bold mb-2">{{ event.title }}</h2>
          <p class="text-gray-700 mb-2">{{ event.description }}</p>
          <p class="text-gray-700 mb-2">
            <strong>Start Time:</strong> {{ event.start_date}}
          </p>
          <p class="text-gray-700 mb-2">
            <strong>End Time:</strong> {{ event.end_date}}
          </p>
        </div>
      </div>
      {% endif %} {% endfor %}
    </div>

    {% if events|length == 0 %}
    <p class="mt-6">No events found.</p>
    {% endif %}

    <div class="mt-8">
      <a
        href="{{ url_for('event.create') }}"
        class="bg-[#2A5CAA] text-white font-bold py-2 px-4 rounded"
        >Create new event</a
      >
    </div>
  </div>
</div>
{% endblock %}